// Next.js API route support: https://nextjs.org/docs/api-routes/introduction

export default (req, res) => {
  res.status(200).json({
    SEO: {
      title: "Wines | Future Ventures Corp",
    },
    title: "Listing Score",
    forms: [
      {
        title: "Tell us a bit about your wine",
        items: [
          {
            show: true,
            depend: null,
            type: "name",
            typeField: "text",
            isRequired: true,
            variant: "simple",
            description: "Help",
            label: "What is the name of this wine?",
          },
          {
            show: true,
            depend: null,
            type: "vintage",
            typeField: "text",
            isRequired: true,
            variant: "simple",
            description: "Help",
            label: "What is the vintage?",
          },
          {
            show: true,
            depend: null,
            type: "note",
            typeField: "text",
            isRequired: false,
            variant: "expand",
            description: "Help",
            label:
              "Any note specific fot this vintage? Examples: Weather, special circumstances, significant or interesting changes made between this vintage and previous vintage(s)?",
          },
          {
            show: true,
            depend: null,
            type: "typeOfWine",
            isRequired: false,
            variant: "simple",
            typeField: "select",
            description: "Help",
            label: "What type of wine is this?",
            selects: [{ label: "" }, { label: "Aperitif" }, { label: "Other" }],
          },
          {
            label: "",
            show: false,
            type: "other",
            description: "",
            isRequired: false,
            variant: "simple",
            typeField: "text",
            depend: "typeOfWine",
          },
        ],
      },
      {
        title: "Color & Body",
        items: [
          {
            show: true,
            depend: null,
            type: "color",
            typeField: "text",
            isRequired: true,
            variant: "simple",
            description: "Help",
            label: "What is the colour of wine?",
          },
          {
            show: true,
            depend: null,
            type: "style",
            typeField: "text",
            isRequired: true,
            variant: "simple",
            description: "Help",
            label: "What is the style",
          },
          {
            show: true,
            depend: null,
            type: "body",
            typeField: "text",
            isRequired: false,
            variant: "simple",
            description: "Help",
            label: "What is the body?",
          },
          {
            show: true,
            depend: null,
            type: "aroma",
            typeField: "text",
            isRequired: false,
            variant: "simple",
            description: "Help",
            label: "What is the aroma?",
          },
          {
            show: true,
            depend: null,
            typeField: "text",
            isRequired: false,
            variant: "simple",
            type: "testingNote",
            description: "Help",
            label: "Do you have any personal testing note?",
          },
        ],
      },
    ],
  });
};
